apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    app: node-app
spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 5000
      nodePort: 30008
  selector:
    app: my-node-app
